### ISSUE TITLE
Executing `make build-simple` gives `Permission denied` error

### ISSUE THREAD

**Issue by Muhammad-Altabba** [bnb-chain/bsc-docker#15]
I am trying to run for dev environment on Linux machine. And I facing an error:

`make build-simple`
> make build-bsc
make[1]: Entering directory '/home/maltabba/repos/experiments/bsc/bsc-docker'
"" docker-compose -f docker-compose.bsc.yml build
sh: 1: : Permission denied
make[1]: *** [Makefile:12: build-bsc] Error 127
make[1]: Leaving directory '/home/maltabba/repos/experiments/bsc/bsc-docker'
make: *** [Makefile:18: build-simple] Error 2

What do you suggest?
Thanks,

**Comment by STdevK** [comment]
Are you using Docker Desktop?

**Comment by Muhammad-Altabba** [comment]
No, I am not.

**Comment by FidelVe** [comment]
having this same issue

```
$ make build-simple
make build-bsc
make[1]: Entering directory '/home/admin-1/devnet/bsc-docker'
"" docker compose -f docker-compose.bsc.yml build
sh: 1: : Permission denied
make[1]: *** [Makefile:12: build-bsc] Error 127
make[1]: Leaving directory '/home/admin-1/devnet/bsc-docker'
make: *** [Makefile:18: build-simple] Error 2
```

**Comment by Muhammad-Altabba** [comment]
@STdevK @ackratos @darren-liu 
Any suggestion please?

**Comment by STdevK** [comment]
@Muhammad-Altabba Can you share the details of docker-compose.bsc.yml?

**Comment by Muhammad-Altabba** [comment]
Hi @STdevK ,
I am following the steps and so my file is the exact as this: https://github.com/bnb-chain/bsc-docker/blob/master/docker-compose.bsc.yml

And here is its content from my computer:
```yaml
version: "3.9"

services:
  bsc-geth:
    build:
      context: .
      dockerfile: Dockerfile.bsc
      args:
        GIT_SOURCE: https://github.com/bnb-chain/bsc.git
        GIT_CHECKOUT_REF: master
    image: bsc-geth:docker-local
```
